### PR TITLE
Add SolidUI

### PR DESCRIPTION
**Pull request by dlimeng**
## Introduction
AI-generated visual prototyping and editing platform, supports 2D and 3D models, combined with LLM (Large Language Model) for fast editing.

https://github.com/CloudOrc/SolidUI

## Core Features

Minimalist process, concise design
Various 2D legends
Various 3D legends
Various 3D scenes
Support multiple data sources
Support Huggingface space
Support plug-in robot
Support SolidUI-Model
Support Large Language Model
Containerized deployment

## co-construction
Code co-construction (front-end, Java, python, etc.)
Community co-construction (content management)
All kinds of donations are available
Users can also

## self introduction

This is, I, I am free, so free and free energy to maintain and initiate

### CODE REVIEW

**Comment by sbusso** [comment]
Thanks @dlimeng for the suggestion. Could you provide some pointers to the langchain part?

**Comment by dlimeng** [comment]
> Thanks @dlimeng for the suggestion. Could you provide some pointers to the langchain part?

Well, the SolidUI development version 0.2.0 is using the langchain chain and content functions

**Comment by sbusso** [comment]
I can see an issue mentioning langchain, but no implementation or use of langchain. I

**Comment by dlimeng** [comment]
> I can see an issue mentioning langchain, but no implementation or use of langchain. I

Hello, this SolidUI 0.2.0 Proposal  https://github.com/CloudOrc/SolidUI/issues/45

**Comment by sbusso** [comment]
A proposal is not enough for this list. A full working code is needed. Closing the PR for now, don't hesitate to submit the project once langchain is implemented

**Comment by dlimeng** [comment]
> A proposal is not enough for this list. A full working code is needed. Closing the PR for now, don't hesitate to submit the project once langchain is implemented

Thank you, after the release of version 0.2.0, apply again

**Pull request closed without merging**
