### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Shahzaib0217**
Removal of redundant links. The same link was added twice by different names.

### CODE REVIEW

**Comment by sbusso** [comment]
@Shahzaib0217 could you point me to the second link?

**Comment by Shahzaib0217** [comment]
image
Yes, I have highlighted both links.

**Comment by sbusso** [comment]
Thanks 🙏🏻 . actually, it would be best to keep the link to the playlist and also it needs to be renamed as Greg apparently renamed his channel.

**Comment by sbusso** [comment]
thanks @Shahzaib0217 I have merged your changes and renamed the playlist.

**Comment by Shahzaib0217** [comment]
Okay, thank you.

**Pull request closed without merging**
