### PR TITLE
docs: add AilingBot - Quickly integrate applications built on Langcha…

### PR DESCRIPTION
**Pull request by ericzhang-cn**
Add a new project to list: A project for quickly integrate applications built on Langchain into IM platforms such as Slack, WeChat Work, Feishu, DingTalk.

### CODE REVIEW

**Comment by sbusso** [comment]
thanks @ericzhang-cn , What does "LangChain friendly" mean? Is langchain optional?

**Comment by ericzhang-cn** [comment]
> thanks @ericzhang-cn , What does "LangChain friendly" mean? Is langchain optional?

Yes. In terms of design, a chat policy only needs to implement how to generate a response message for a user's request message. Whether or not the chat policy uses LangChain or even LLM is optional (for example, a completely rule-based policy can be developed).However, in practice, almost all of our policies are developed based on LangChain and LLM.

**Comment by sbusso** [comment]
Gotcha, thanks for the explanation. Looks like a very interesting platform, do you think it could be in the tools section, no-code, or service?

**Comment by ericzhang-cn** [comment]
> Gotcha, thanks for the explanation. Looks like a very interesting platform, do you think it could be in the tools section, no-code, or service?

Thank you for your reply. I have carefully reviewed it, and I think the services under the tools section are more appropriate. As I understand it, the low-code projects focus more on the low-code platform itself for Langchain, while this project's main purpose is to facilitate the integration of the applications already built on Langchain into IM tools such as Slack.

**Comment by sbusso** [comment]
@ericzhang-cn you are right service is better, could you update the PR?

**Comment by sbusso** [comment]
thanks @ericzhang-cn  🙏🏻

**Comment by ericzhang-cn** [comment]
> @ericzhang-cn you are right service is better, could you update the PR?

Sure! I have completed the update. Thanks!

**Pull request merged**
